### ISSUE TITLE
Disable price exemptions for locally submitted transactions for testnet

### ISSUE THREAD

**Issue by nicolegys** [bane-labs/go-ethereum#137] opened 2024-02-21 11:35 UTC
Tx with a gas price of 0 can be sent to node pending pool through rpc, which is recognized by the Geth as a `local` tx.

https://xt2scan.ngd.network/tx/0xf12ff511b8cfde731bd8472ada26ee72938287d475ed9c032462efce05a2958f
![1708510704601](https://github.com/bane-labs/go-ethereum/assets/43694095/1ec30cb4-1a24-40fb-9064-0c869b5b96a0)

Of course, it cannot be accepted by other nodes through p2p, but it will stay in the txpool of the rpc node which it is sent to.
In my privnet, I sent batch of txs to the rpc node, and the Geth consumed cpu resources during the process.

![1708512639882](https://github.com/bane-labs/go-ethereum/assets/43694095/4e8ae873-9cbc-42e4-95a9-c9ad8da91b4b)

![1708508970045](https://github.com/bane-labs/go-ethereum/assets/43694095/2867cc0a-15b6-4a8d-b786-71df8a38173d)

Also, since the node stores local transactions to the disk in `transactions.rlp` file, if we restart the node, it really consumes time and cpu to load them from the disk.

In testnet, we expose the rpc port directly to the user, so we'd better add some restrictions on the local transactions.
I found `--txpool.nolocals` in Geth docs, but it doesn't seem to be working. I only see that it does not store `transactions.rlp`, transactions with a gas price of 0 can still be accepted by txpool, maybe I missed something.
```
 --txpool.nolocals                   (default: false)                   ($GETH_TXPOOL_NOLOCALS)
          Disables price exemptions for locally submitted transactions
```

**Comment by AnnaShaleva** [comment] 2024-04-10 09:01
I did some digging, here are the results:

### Explanation

#### About the minimum GAS price

First of all, minimum required GAS price check is present in the node code, on the level of state-independent generic mempool verification, along with a batch of other GAS price/tip/cap related checks:
https://github.com/bane-labs/go-ethereum/blob/6cd26f231675ad8c229ce4fc8644d2f3d29c3d6a/core/txpool/validation.go#L89-L110

So the check that should be triggered by the proposed transaction is at the line 108 in this code snippet. `MinTip` is a customizable option of transaction pool. For both legacy and blob transaction pools this value is being set via setter interface:
https://github.com/bane-labs/go-ethereum/blob/6cd26f231675ad8c229ce4fc8644d2f3d29c3d6a/core/txpool/txpool.go#L279-L285

So in the current implementation minimum GAS price is a mempool characteristics that should be customize by the node operator. There are two ways to customize it: via CLI flag during node start (flag `miner.gasprice`, ref. [link](https://github.com/bane-labs/go-ethereum/blob/6cd26f231675ad8c229ce4fc8644d2f3d29c3d6a/cmd/utils/flags.go#L439)) or via call to `miner` node API if the node is already running (`setGasPrice` method with some hex-encoded big integer value, ref. [link](https://github.com/bane-labs/go-ethereum/blob/6cd26f231675ad8c229ce4fc8644d2f3d29c3d6a/eth/api_miner.go#L61), but keep in mind that `miner` API should be enabled on the target node to use this method).

Here's the example of how GAS price restriction works in tests:
https://github.com/bane-labs/go-ethereum/blob/6cd26f231675ad8c229ce4fc8644d2f3d29c3d6a/core/txpool/legacypool/legacypool_test.go#L1496

#### About the local transactions

> I found `--txpool.nolocals` in Geth docs, but it doesn't seem to be working.

This flag is the appropriate one, it disallows such "free" transactions:
https://github.com/bane-labs/go-ethereum/blob/6cd26f231675ad8c229ce4fc8644d2f3d29c3d6a/core/txpool/legacypool/legacypool.go#L597-L601

The reason this flag is not working is in fact that the node likely doesn't have the minimum GAS price limit set. So this flag will work in case if the node's minimum GAS price limit will be set as described above. @nicolegys, could you please check it?

#### About the Policy systemcontract minGASPrice constraint

Policy system contract (#7) contains system-wide `minGASPrice` constraint feature. It is integrated into both state-dependant txpool transaction verification and state verification in #6:
https://github.com/bane-labs/go-ethereum/blob/d82cb30556a562993c32ba9ca7b59e960f2cac4a/core/txpool/validation.go#L204-L209

So once we merge #6, the minimum GAS price will be enforced on the system level.

### Solution

I'd suggest to set both the `--miner.gasprice` value and `--txpool.nolocals` during testnet node start, it seems to be the best solution, but I can't do anything about it since I'm not a node operator. I think we need to ask @steven1227's team to start T3 nodes with these two additional flags.

So there's nothing we should change in the node code to close this issue. @roman-khimov, agree?

**Comment by roman-khimov** [comment] 2024-04-11 18:44
Nothing specific to do here except for the check after #6 merge. Additional configuration options are OK for T3 as well.

**Comment by AnnaShaleva** [comment] 2024-04-12 07:15
>Nothing specific to do here except for the check after https://github.com/bane-labs/go-ethereum/pull/6 merge.

It is already confirmed by Nicole, so we just need to run T3 nodes with proper flags. Thus, I'm closing this issue as completed.

**Closed as completed by AnnaShaleva** 2024-04-12 07:15 UTC
Labels: bug, config
