### ISSUE TITLE
Frequent chain reorg detected

### ISSUE THREAD

**Issue by nicolegys** [bane-labs/go-ethereum#69] opened 2023-12-22 09:19 UTC
In 4-cn privnet, nodes frequently detect chain reorg and then reimport several blocks.

![1703236063747](https://github.com/bane-labs/go-ethereum/assets/43694095/5a396f47-a5aa-4140-9f13-71e83b3b47b0)

Something strange is that, if I stop one CN，the `reorg` will disappear, then start this CN, it appears again.

This screenshot captures reorg information from the node log, and CN1 is offline during block(228, 1656):
![1703236522277](https://github.com/bane-labs/go-ethereum/assets/43694095/f032af12-bf68-48eb-87f9-55ab5a035fe1)

**Comment by AnnaShaleva** [comment] 2023-12-22 13:48
> nodes frequently detect chain reorg 

This is the direct consequences of our delayed block hash finality issue. It's described in https://github.com/bane-labs/go-ethereum/issues/48, and in short words, the problem is that every consensus node collects block's signature from available Commit messages (3 out of 4 for 4-nodes consensus). The set of commit messages can be different at every node, thus, the resulting block hash is also different.

> Something strange is that, if I stop one CN，the reorg will disappear, then start this CN, it appears again.

Reorg disappears on 3-nodes privnet because the set of Commit messages always contains same commits (we need at least 3 out of 4 commits and these 3 commits are equal, because 4th node is down).

Thus, this behaviour is completely expected and I'd suggest to close this issue because we have #48.

**Comment by roman-khimov** [comment] 2023-12-22 13:50
Duplicates #48, yes.

**Closed as not planned** 2023-12-22 13:50 UTC
